// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int Times = Integer.parseInt(args[0]);
		double lower = 0;
		double upper = 0;
		for (int i = 0; i < Times; i++) {
		if (Math.random() < 0.5) {
		    lower++;
		} else {
		    upper++;}}

		double Ratio;
		System.out.println("Lower half count: " + lower);
		System.out.println("Upper half count: " + upper);
		
		if (lower > upper) {
			Ratio =  (double)(lower /upper);}
			else {
			Ratio = (double) (upper / lower);}
			
		System.out.println("Ratio: " + Ratio);

	
	}
}
